// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0gd-KnaSMYLdd9MlYBDvxBZOfkdq32lU',
    appId: '1:448415422334:web:0703219a33329acad3c52f',
    messagingSenderId: '448415422334',
    projectId: 'iitpatnabus-c8785',
    authDomain: 'iitpatnabus-c8785.firebaseapp.com',
    storageBucket: 'iitpatnabus-c8785.appspot.com',
    measurementId: 'G-9YPB0BGNBY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiTPSY3pycxtohO1lw23jyZzxyLQN55ew',
    appId: '1:448415422334:android:02f3467c159fcefcd3c52f',
    messagingSenderId: '448415422334',
    projectId: 'iitpatnabus-c8785',
    storageBucket: 'iitpatnabus-c8785.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAO3D_zVtw4DOdHkcV0jTBZvXKpCUpNeqo',
    appId: '1:448415422334:ios:f592db426acf5f69d3c52f',
    messagingSenderId: '448415422334',
    projectId: 'iitpatnabus-c8785',
    storageBucket: 'iitpatnabus-c8785.appspot.com',
    iosClientId: '448415422334-c35k09tm3kfthkv6ru7ak6nqhf2rvhg9.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAO3D_zVtw4DOdHkcV0jTBZvXKpCUpNeqo',
    appId: '1:448415422334:ios:f592db426acf5f69d3c52f',
    messagingSenderId: '448415422334',
    projectId: 'iitpatnabus-c8785',
    storageBucket: 'iitpatnabus-c8785.appspot.com',
    iosClientId: '448415422334-c35k09tm3kfthkv6ru7ak6nqhf2rvhg9.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
